In [25]:
import sys

sys.path.append("..")

import joblib
import polars as pl

# Predict Games

model_path: str
    Path to a pickled tuple of type (estimator, train_cols)

predict_path: str
    Path to the parquet file containing the data to be predicted.

league_id: int
    Legaue_id of the matches to be predited.
    
match_day: int
    Match day to be predicted.

In [26]:
model_path = "../models/lgbm.pkl"
predict_path = "/home/fabian/Project-Data/AK-Tippspiel/openligadb/openligadb_result_class_predict.parquet"
league_id = 4741
match_day = 13

## Load model and train cols

In [27]:
model, train_cols = joblib.load(model_path)
model.estimator

LGBMClassifier(learning_rate=0.001, n_estimators=3000, num_leaves=8,
               objective='multiclass')

## Load data to be predicted

In [28]:
df_predict = (
    pl.scan_parquet(predict_path)
    .filter((pl.col("league_id") == league_id) & (pl.col("match_day") == match_day))
    .collect()
)
df_predict

shape: (9, 59)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ match_id ┆ league_id ┆ match_day ┆ team_id_1 ┆ … ┆ goals_con ┆ goals_dif ┆ goals_dif ┆ goals_dif │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ceded_avg ┆ f_last_3_ ┆ f_last_5_ ┆ f_avg_2   │
│ i64      ┆ i64       ┆ i64       ┆ i64       ┆   ┆ _2        ┆ games_2   ┆ games_2   ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆ i64       ┆ i64       ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 72323    ┆ 4741      ┆ 13        ┆ 16        ┆ … ┆ 0.916667  ┆ -2        ┆ -5        ┆ -0.083333 │
│ 72322    ┆ 4741      ┆ 13        ┆ 6         ┆ … ┆ 1.25      ┆ -1        ┆ 1         ┆ -0.416667 │
│ 72324    ┆ 4741      ┆ 13        ┆ 40        ┆ … ┆ 2.0       ┆ -9        ┆ -10       ┆ -0.75     │
│ 72325    ┆ 4741      ┆ 13        ┆ 91        ┆ … ┆ 1.916667  ┆ -2        ┆ -1        ┆ -0.75     │
│ 72329    ┆ 4741      ┆ 13        ┆ 129       ┆ … ┆ 2.0       ┆ 0         ┆ -3        ┆ -0.416667 │
│ 72330    ┆ 4741      ┆ 13        ┆ 104       ┆ … ┆ 1.166667  ┆ -5        ┆ -4        ┆ 0.416667  │
│ 72328    ┆ 4741      ┆ 13        ┆ 87        ┆ … ┆ 1.583333  ┆ 2         ┆ 2         ┆ 0.333333  │
│ 72327    ┆ 4741      ┆ 13        ┆ 131       ┆ … ┆ 1.166667  ┆ 7         ┆ 7         ┆ 0.5       │
│ 72326    ┆ 4741      ┆ 13        ┆ 123       ┆ … ┆ 1.333333  ┆ -2        ┆ -4        ┆ 0.0       │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Prediction

In [29]:
df_predict = df_predict.with_columns(model.predict(df_predict[train_cols]))
df_predict.select(
    ["team_name_1", "team_name_2", "goals_team_1_pred_lgbm", "goals_team_2_pred_lgbm"]
)

shape: (9, 4)
┌─────────────────────┬───────────────────────┬────────────────────────┬────────────────────────┐
│ team_name_1         ┆ team_name_2           ┆ goals_team_1_pred_lgbm ┆ goals_team_2_pred_lgbm │
│ ---                 ┆ ---                   ┆ ---                    ┆ ---                    │
│ str                 ┆ str                   ┆ i64                    ┆ i64                    │
╞═════════════════════╪═══════════════════════╪════════════════════════╪════════════════════════╡
│ VfB Stuttgart       ┆ 1. FC Union Berlin    ┆ 1                      ┆ 0                      │
│ Bayer Leverkusen    ┆ FC St. Pauli          ┆ 1                      ┆ 0                      │
│ FC Bayern München   ┆ 1. FC Heidenheim 1846 ┆ 1                      ┆ 0                      │
│ Eintracht Frankfurt ┆ FC Augsburg           ┆ 1                      ┆ 0                      │
│ VfL Bochum          ┆ Werder Bremen         ┆ 1                      ┆ 2                      │
│ Holstein Kiel       ┆ RB Leipzig            ┆ 1                      ┆ 2                      │
│ Borussia            ┆ Borussia Dortmund     ┆ 1                      ┆ 0                      │
│ Mönchengladbach     ┆                       ┆                        ┆                        │
│ VfL Wolfsburg       ┆ 1. FSV Mainz 05       ┆ 1                      ┆ 0                      │
│ TSG 1899 Hoffenheim ┆ SC Freiburg           ┆ 1                      ┆ 0                      │
└─────────────────────┴───────────────────────┴────────────────────────┴────────────────────────┘